export const USER_CONVERSATIONS = 'USER_CONVERSATIONS';
export const CONVERSATION_MESSAGES = 'CONVERSATION_MESSAGES';
export const SEND_MESSAGES = 'SEND_MESSAGES';
export const SPACE_DETAILS = 'SPACE_DETAILS';
export const CLEAR_CHAT = 'CLEAR_CHAT';
